### ISSUE TITLE
Adjust new website UI

### ISSUE THREAD

**Issue by albogabriel** [pixelated/website#40]
Taken from discussions on #32 :

> The hive background for the home page doesn't provide enough contrast with the text. Some ways to improve that would be:
> a) Change the background. We can make the hive more transparent so the background for the text is a bit more solid, for instance. We could also remove the hive background altogether, but I personally think it's cool to leave it there to repeat the logo.
> b) Make the text - especially the three clickable items - white instead of grey.
> 
> The three clickable items could call for action more clearly. One possibility is to have them stand out by having them framed/surrounded with a solid background - say, round.
> 
> The letter icon is in a different style when compared to other icons we use - which tend to be more solid. I'd change it to the fa-envelope font-awesome one. (http://fortawesome.github.io/Font-Awesome/cheatsheet/)
> 
> The "how can I help" icon is a bit misleading for me. I'd change it for the "user" (or "group") font-awesome icon.
> 
> Currently, the margins to left and right are around 20% each for the content of the page. I'd use something closer to 14% to distribute elements a bit more and use real estate better.
> 
> On the FAQ session I'd definitely change the hyperlink colors from orange to something else - maybe dark blue - so it brings a clearer contrast with the white background.

**Comment by pereiragislene** [comment]
Hey @felixhammerl, in #32 you said you used the SVG version of Font Awesome. Is there a specific reason for that? The icon/text version would be easier to customize. Is that ok if I change it? Thanks!

**Comment by felixhammerl** [comment]
@pereiragislene RE SVG vs. icon font: Yes, there is. Chris Coyer [explains this nicely in a blog post](https://css-tricks.com/icon-fonts-vs-svg/). For me, it boils down to: 
* Fewer networks roundtrips
* One less CSS library
* One less font thingy to maintain
* Load time: Having to load the entire font vs. selective SVGs that come *injected into* the markup
* Having the SVGs ready when the content is loaded, also weird FOUT effects on slow connections

A more philosophical point: It's 2016, I vote we bury icon fonts :) Icons are what SVGs were made for :)

**Comment by pereiragislene** [comment]
@felixhammerl: I got your point and they make sense. I read the article (thanks for sharing), but I don't see any performance issues related to the use of Font Awesome as a CSS class library in this specific scenario. 
Also, I'm not sure if it's worth the higher effort we would have to customize the SVG images, comparing to a font that is easilly customizable via CSS.
@albogabriel, any opinions about this?

**Comment by felixhammerl** [comment]
It's just one more file to get from the server. No biggie, but unnecessary.
You can style SVG via CSS, that's the beauty of it. In the end, it's just
markup, and your browser can handle/style/paint that really well :)

**Comment by pereiragislene** [comment]
@felixhammerl: Ok, you win :) 
I've reverted the icons back to SVG and also changed the envelope and "How can I help" icons.
Thanks.

**Comment by felixhammerl** [comment]
IMHO the sidebar should be sticky on the bottom, not scrolling as it is now...

**Comment by pereiragislene** [comment]
@felixhammerl: I like the idea. Do you have any suggestion about the background color in case it's sticky to the bottom? We need to give the user the feeling that there's more text behind it.

**Comment by felixhammerl** [comment]
if you look closely, you'll notice that the nav bar has a [very slight .9 alpha setting in the background color](https://github.com/pixelated/website/blob/master/_sass/modules/_navigation.scss#L3). We could do the same with the footer.

I'd make it the same height as the navbar, for visual simplicity.

as for positioning, there's a bunch of alternatives. If you choose to position it absolute (as the navbar), you'll need to offset the content [as i did with the content](https://github.com/pixelated/website/blob/master/_sass/base/_scaffolding.scss#L25-L26)

**Comment by albogabriel** [comment]
I like those ideas, @felixhammerl! I'll start trying them out now.

Thanks!

**Comment by felixhammerl** [comment]
we still need to offset the content ... will do that later today :)

<img width="413" alt="screen shot 2016-02-16 at 1 13 44 pm" src="https://cloud.githubusercontent.com/assets/1818340/13075961/3a9a10dc-d4af-11e5-9dbc-e30a05c429e2.png">

**Comment by pereiragislene** [comment]
@felixhammerl: I guess that setting the ".home" padding-bottom to 50px should do the trick. What do you think?

**Comment by felixhammerl** [comment]
fixed with https://github.com/pixelated/website/commit/9207465d48c205bbbce781aa6254d0cf24a4ebe1
