### ISSUE TITLE
General hacknight documentation page

### ISSUE THREAD

**Issue by varac** [pixelated/website#43]
We should have a startpage for everybody joining the hacknight, see https://cryptohack.net/post/10th-feb-hacknight-welcome.html for an example

**Comment by varac** [comment]
see https://github.com/cryptohack/cryptohack.net/blob/master/content/post/10th-feb-hacknight-welcome.md for the raw content

**Comment by felixhammerl** [comment]
i improved a bit upon our existing onboarding guide: https://github.com/pixelated/pixelated-user-agent/
