### ISSUE TITLE
Index Email Link

### ISSUE THREAD

**Issue by barreyro** [pixelated/website#50]
On the [index page](https://pixelated-project.org/), the email icon link on the left side of the page opens a blank browser window. I expected it to open my e-mail carrier. I believe this can be fixed by setting the HTML attribute, `target`, to be `" "` instead of `"_blank"`

![screen shot 2016-05-17 at 11 12 49 pm](https://cloud.githubusercontent.com/assets/8381409/15346385/8730a42e-1c85-11e6-9f05-171e30f8618e.png)

**Comment by cacarrara** [comment]
Thank you so much, @barreyro.

It's fixed :)
